- name: Create temporary K9s directory
  ansible.builtin.file:
    state: directory
    path: "/tmp/k9s"

- name: Unpack K9s
  ansible.builtin.unarchive:
    src: "https://github.com/derailed/k9s/releases/download/v0.32.4/k9s_Linux_amd64.tar.gz"
    dest: "/tmp/k9s"
    remote_src: true

- name: Install K9s
  become: true
  ansible.builtin.copy:
    src: "/tmp/k9s/k9s"
    dest: "/usr/bin/k9s"
    mode: "+x"
    remote_src: true

- name: Cleaning Up temporary K9s installation files
  become: true
  ansible.builtin.file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - "k9s"
#
- name: Stop firewall service
  become: true
  ansible.builtin.systemd:
    name: ufw
    state: stopped
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install pip
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  with_items:
    - python3-pip
    - python3-venv

- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes
    virtualenv: /home/aveiga/k3s-venv
    virtualenv_command: /usr/bin/python3 -m venv
