pre-requisites:
	ansible-playbook pre-requisites.yaml --ask-vault-pass

install-k3s:
	ansible-playbook k3s-install.yaml --ask-vault-pass

install-base-workload:
	ansible-playbook k3s-install-base-workload.yaml --ask-vault-pass

uninstall:
	ansible-playbook k3s-uninstall.yaml --ask-vault-pass

shutdown:
	ansible-playbook shutdown.yaml --ask-vault-pass